"""
NL2Shell Expert Pairs — Senior Engineer Quality
==================================================
Combined from multiple AI agents (Amp, Codex, Gemini, Cursor)
and hand-curated examples. Each pair represents how a 10+ year
senior engineer would write the command.

Total: 961 expert-quality pairs
"""

EXPERT_PAIRS: list[tuple[str, str]] = [
    (
        "redirect only the stderr of a script through a grep filter while keeping stdout intact",
        "./build.sh 3>&1 1>&2 2>&3 | grep -i fail",
    ),
    (
        "swap stderr and stdout streams using a temporary file descriptor 3",
        "exec 3>&1; ./script.sh 2>&1 1>&3 3>&- | sed 's/^/ERR: /' >&2; exec 3>&-",
    ),
    (
        "check exit code of first command in a pipe",
        'gzip < big.log | wc -c; echo "gzip exit: ${PIPESTATUS[0]}"',
    ),
    ("fail if any command in a pipeline fails", "set -o pipefail && make build | tee build.log"),
    (
        "capture all pipeline exit codes after running",
        'cmd1 | cmd2 | cmd3; echo "exits: ${PIPESTATUS[*]}"',
    ),
    (
        "assert pipeline succeeded and print status array",
        "pg_dump mydb | gzip > mydb.sql.gz; [[ ${PIPESTATUS[0]} -eq 0 ]] || echo 'pg_dump failed'",
    ),
    (
        "tee command output to two different files at once",
        "./deploy.sh | tee deploy.log >(grep ERROR > errors.log)",
    ),
    (
        "tee stdout to file while also sending to a log aggregator",
        "./app.sh 2>&1 | tee -a app.log | logger -t myapp",
    ),
    (
        "fan output to three consumers via process substitution",
        "cat access.log | tee >(grep 200 | wc -l > ok.txt) >(grep 500 | wc -l > err.txt) >/dev/null",
    ),
    (
        "tee stderr to a file while stdout continues to terminal",
        "{ ./run.sh 2>&1 1>&3 | tee errors.log 1>&2; } 3>&1",
    ),
    (
        "diff two command outputs and fail if they differ",
        "diff <(./expected.sh 2>/dev/null) <(./actual.sh 2>/dev/null) || exit 1",
    ),
    (
        "feed process substitution output into while loop",
        'while IFS= read -r line; do echo "got: $line"; done < <(kubectl get pods 2>/dev/null)',
    ),
    (
        "capture stderr of process substitution separately",
        "diff <(cmd1 2>cmd1_err.log) <(cmd2 2>cmd2_err.log)",
    ),
    (
        "write stdout to one file and stderr to another without shell builtins",
        "./app 1>out.log 2>err.log",
    ),
    (
        "redirect only fd 3 to a file for custom logging",
        "exec 3>debug.log; echo 'debug info' >&3; exec 3>&-",
    ),
    ("duplicate stdout to a log file using exec redirect", "exec > >(tee -a session.log) 2>&1"),
    (
        "send stdout to file and stderr to a separate command",
        "./run.sh 2> >(grep -v DeprecationWarning >&2)",
    ),
    (
        "capture command output to variable while still printing it",
        "output=$(./check.sh | tee /dev/stderr)",
    ),
    (
        "print progress to stderr and final result to stdout",
        "{ echo 'working...' >&2; sleep 1; echo 'done'; }",
    ),
    ("redirect stdout to stderr for a single echo", "echo 'this goes to stderr' >&2"),
    (
        "create a worktree for a hotfix branch without switching",
        "git worktree add ../hotfix-tree hotfix/critical-bug",
    ),
    ("list all active worktrees with their paths", "git worktree list --porcelain"),
    (
        "remove a worktree and prune stale references",
        "git worktree remove ../hotfix-tree && git worktree prune",
    ),
    (
        "find the commit hash before an accidental reset",
        "git reflog | grep 'reset\\|checkout' | head -20",
    ),
    ("recover a dropped stash using reflog", "git reflog | grep 'stash' | head -5"),
    ("restore branch to state 3 moves ago via reflog", "git reset --hard HEAD@{3}"),
    ("interactively stash only selected hunks", "git stash push -p -m 'partial wip: auth changes'"),
    ("stash only a specific file", "git stash push -m 'wip: config only' -- config/settings.py"),
    (
        "search commit messages for a pattern across all branches",
        "git log --all --oneline --grep='hotfix' --regexp-ignore-case",
    ),
    (
        "find all commits that added or removed a function name",
        "git log -S 'authenticate_user' --all --oneline --source",
    ),
    ("search commit diffs for a regex pattern", "git log -G 'password\\s*=' --oneline --all"),
    ("blame a specific line range in a file", "git blame -L 45,72 src/auth/jwt.ts"),
    ("blame ignoring whitespace-only changes", "git blame -w -L 10,30 src/api/routes.py"),
    ("show the content of a file at a specific commit", "git show abc1234:src/config.ts"),
    (
        "list all files that were changed in a specific commit",
        "git diff-tree --no-commit-id -r --name-only abc1234",
    ),
    (
        "clone a repo and initialize all submodules recursively",
        "git clone --recurse-submodules https://github.com/org/repo.git",
    ),
    (
        "update all submodules to their latest tracked commit",
        "git submodule update --init --recursive --remote",
    ),
    ("show which submodule commit is checked out", "git submodule status --recursive"),
    (
        "enable sparse checkout and fetch only a specific directory",
        "git sparse-checkout init --cone && git sparse-checkout set src/api",
    ),
    (
        "add another directory to an existing sparse checkout",
        "git sparse-checkout add docs/architecture",
    ),
    ("get all pods across all namespaces with node assignment", "kubectl get pods -A -o wide"),
    (
        "follow logs of a crashing pod and restart on failure",
        "kubectl logs -f --previous deployment/api-server -n production",
    ),
    (
        "describe a failing pod to see events and status",
        "kubectl describe pod api-server-6d8f7b9-xkpqz -n production",
    ),
    (
        "exec into a running pod container",
        "kubectl exec -it deployment/api-server -n production -- /bin/sh",
    ),
    (
        "get all pods in CrashLoopBackOff state",
        "kubectl get pods -A --field-selector=status.phase=Running | grep CrashLoop",
    ),
    (
        "watch pod rollout status in real time",
        "kubectl rollout status deployment/api-server -n production --timeout=5m",
    ),
    (
        "port-forward a service to localhost for debugging",
        "kubectl port-forward svc/postgres 5432:5432 -n staging",
    ),
    (
        "get resource limits and requests for all pods in a namespace",
        "kubectl get pods -n production -o json | jq '.items[].spec.containers[].resources'",
    ),
    (
        "force delete a stuck terminating pod",
        "kubectl delete pod stuck-pod-xyz -n production --grace-period=0 --force",
    ),
    (
        "apply a manifest and wait for rollout to complete",
        "kubectl apply -f k8s/deployment.yaml && kubectl rollout status deployment/api-server -n production",
    ),
    (
        "list all running EC2 instances with their IPs",
        "aws ec2 describe-instances --filters 'Name=instance-state-name,Values=running' --query 'Reservations[*].Instances[*].[InstanceId,PublicIpAddress,Tags[?Key==`Name`].Value|[0]]' --output table",
    ),
    (
        "tail CloudWatch logs for a Lambda function",
        "aws logs tail /aws/lambda/my-function --follow --format short",
    ),
    (
        "copy a file to S3 with server-side encryption",
        "aws s3 cp secrets.json s3://my-bucket/config/secrets.json --sse aws:kms",
    ),
    (
        "invoke a Lambda function and show the response",
        'aws lambda invoke --function-name my-function --payload \'{"key":"value"}\' /tmp/out.json && cat /tmp/out.json',
    ),
    (
        "get a secret value from Secrets Manager",
        "aws secretsmanager get-secret-value --secret-id prod/db/password --query SecretString --output text",
    ),
    (
        "list all Cloud Run services across all regions",
        "gcloud run services list --platform managed --format='table(name,region,status.url)'",
    ),
    (
        "stream Cloud Run logs in real time",
        "gcloud beta run services logs tail my-service --region us-central1",
    ),
    (
        "deploy a container image to Cloud Run",
        "gcloud run deploy my-service --image gcr.io/project/image:latest --region us-central1 --allow-unauthenticated",
    ),
    (
        "get the external IP of a GKE load balancer service",
        "gcloud compute forwarding-rules list --filter='name~my-service' --format='value(IPAddress)'",
    ),
    (
        "set a Cloud Run environment variable without redeploying image",
        "gcloud run services update my-service --set-env-vars DB_URL=postgres://host/db --region us-central1",
    ),
    (
        "run a SQL query from the command line without interactive prompt",
        "psql -U myuser -d mydb -c 'SELECT count(*) FROM users WHERE active = true;'",
    ),
    (
        "export a table to CSV from psql",
        "psql -U myuser -d mydb -c '\\COPY users TO STDOUT WITH CSV HEADER' > users.csv",
    ),
    (
        "run a SQL file against a database non-interactively",
        "psql -U myuser -d mydb -f migrations/001_add_index.sql",
    ),
    (
        "show all table sizes in a PostgreSQL database",
        "psql -U myuser -d mydb -c 'SELECT relname, pg_size_pretty(pg_total_relation_size(oid)) FROM pg_class WHERE relkind=\\'r\\' ORDER BY pg_total_relation_size(oid) DESC LIMIT 20;'",
    ),
    (
        "list all running queries in PostgreSQL",
        "psql -U myuser -d mydb -c 'SELECT pid, now()-query_start AS duration, state, query FROM pg_stat_activity WHERE state != \\'idle\\' ORDER BY duration DESC;'",
    ),
    (
        "kill a long-running PostgreSQL query by pid",
        "psql -U myuser -d mydb -c 'SELECT pg_terminate_backend(12345);'",
    ),
    (
        "query a SQLite database file from the command line",
        "sqlite3 app.db 'SELECT * FROM sessions WHERE expires_at < datetime(\"now\");'",
    ),
    (
        "export SQLite table to CSV",
        "sqlite3 -header -csv app.db 'SELECT * FROM events ORDER BY created_at DESC LIMIT 1000;' > events.csv",
    ),
    ("show all tables in a SQLite database", "sqlite3 app.db '.tables'"),
    ("check SQLite database integrity", "sqlite3 app.db 'PRAGMA integrity_check;'"),
    ("run a vacuum on a SQLite database to reclaim space", "sqlite3 app.db 'VACUUM;'"),
    (
        "run a MySQL query from the command line",
        "mysql -u root -p'$DB_PASS' mydb -e 'SELECT table_name, table_rows FROM information_schema.tables WHERE table_schema = database();'",
    ),
    (
        "dump a single MySQL table to SQL file",
        "mysqldump -u root -p'$DB_PASS' mydb users > users_backup.sql",
    ),
    ("import a SQL dump into MySQL", "mysql -u root -p'$DB_PASS' mydb < backup.sql"),
    (
        "get all keys matching a pattern in Redis",
        "redis-cli --scan --pattern 'session:*' | head -20",
    ),
    ("flush all keys in a specific Redis database", "redis-cli -n 2 FLUSHDB"),
    (
        "monitor live Redis commands in real time",
        "redis-cli MONITOR | grep -i 'set\\|get' | head -50",
    ),
    (
        "check Redis memory usage and eviction stats",
        "redis-cli INFO memory | grep -E 'used_memory_human|maxmemory_human|evicted_keys'",
    ),
    (
        "count documents in a MongoDB collection from the shell",
        "mongosh mydb --eval 'db.users.countDocuments({active: true})'",
    ),
    (
        "export a MongoDB collection to JSON via mongosh",
        "mongosh mydb --eval 'JSON.stringify(db.events.find({},{_id:0}).toArray())' --quiet > events.json",
    ),
    ("generate a 4096-bit RSA private key", "openssl genrsa -out private.key 4096"),
    (
        "create a certificate signing request from an existing key",
        "openssl req -new -key private.key -out request.csr -subj '/CN=example.com/O=MyOrg/C=US'",
    ),
    ("view the details of an x509 certificate", "openssl x509 -in cert.pem -noout -text"),
    (
        "verify a certificate matches its private key",
        "diff <(openssl x509 -in cert.pem -pubkey -noout) <(openssl rsa -in private.key -pubout 2>/dev/null)",
    ),
    (
        "convert a PEM certificate to DER format",
        "openssl x509 -in cert.pem -outform DER -out cert.der",
    ),
    (
        "encrypt a file for a specific recipient with GPG",
        "gpg --encrypt --recipient user@example.com --output secret.gpg plaintext.txt",
    ),
    ("decrypt a GPG-encrypted file", "gpg --decrypt --output plaintext.txt secret.gpg"),
    ("sign a file with your GPG key", "gpg --detach-sign --armor --output file.sig file.txt"),
    ("verify a GPG detached signature", "gpg --verify file.sig file.txt"),
    ("list all keys in your GPG keyring", "gpg --list-keys --keyid-format LONG"),
    (
        "generate an ed25519 SSH key with a comment",
        "ssh-keygen -t ed25519 -C 'user@host-$(date +%Y%m%d)' -f ~/.ssh/id_ed25519_new",
    ),
    ("add a private key to the SSH agent for the session", "ssh-add -t 3600 ~/.ssh/id_ed25519"),
    ("list all identities loaded in the SSH agent", "ssh-add -l"),
    (
        "copy your public key to a remote server",
        "ssh-copy-id -i ~/.ssh/id_ed25519.pub user@remote.host",
    ),
    ("connect to a host with agent forwarding enabled", "ssh -A user@bastion.example.com"),
    ("compute SHA-256 checksum of a file", "shasum -a 256 installer.pkg"),
    (
        "verify a file against a published SHA-256 checksum",
        "echo 'abc123...  installer.pkg' | shasum -a 256 -c -",
    ),
    (
        "generate MD5 checksums for all files in a directory",
        "find . -type f -print0 | xargs -0 md5 -r 2>/dev/null | sort > checksums.md5",
    ),
    ("lock down SSH private key permissions", "chmod 600 ~/.ssh/id_ed25519 && chmod 700 ~/.ssh"),
    (
        "recursively set correct web-root ownership and permissions",
        "find /var/www/html -type d -exec chmod 755 {} + && find /var/www/html -type f -exec chmod 644 {} +",
    ),
    (
        "trace all file-open syscalls made by a running process",
        "strace -p $(pgrep -n nginx) -e trace=openat,open 2>&1 | head -50",
    ),
    (
        "trace network syscalls of a new process invocation",
        "strace -e trace=network,socket -f ./server 2>&1 | head -100",
    ),
    ("summarise syscall counts and time for a command", "strace -c -f ./app 2>&1 | tail -20"),
    (
        "trace file opens on macOS using dtruss",
        "sudo dtruss -f -t open_nocancel -p $(pgrep -n node) 2>&1 | head -50",
    ),
    (
        "record a CPU perf profile for 10 seconds",
        "sudo perf record -F 99 -g -p $(pgrep app) -- sleep 10",
    ),
    (
        "generate a flamegraph from a perf.data recording",
        "sudo perf script | stackcollapse-perf.pl | flamegraph.pl > flamegraph.svg",
    ),
    (
        "show top CPU-consuming functions in perf report",
        "sudo perf report --stdio --sort=dso,symbol | head -40",
    ),
    (
        "run a command three times and show real elapsed time each run",
        "for i in 1 2 3; do { time ./benchmark; } 2>&1 | grep real; done",
    ),
    ("measure wall clock and CPU time of a pipeline", "{ time (gzip -c largefile | wc -c); } 2>&1"),
    (
        "benchmark two implementations and compare",
        "hyperfine --warmup 5 './impl_a input.dat' './impl_b input.dat' --export-markdown results.md",
    ),
    (
        "run a program under valgrind memcheck and show leak summary",
        "valgrind --leak-check=full --show-leak-kinds=all --track-origins=yes ./app 2>&1 | tail -30",
    ),
    (
        "profile heap allocations with valgrind massif",
        "valgrind --tool=massif --pages-as-heap=yes ./app && ms_print massif.out.* | head -60",
    ),
    (
        "check for memory leaks on macOS with leaks tool",
        "leaks --atExit -- ./app 2>&1 | grep 'leaks for'",
    ),
    (
        "run heap profiling with gperftools on Linux",
        "HEAPPROFILE=/tmp/heap.prof LD_PRELOAD=/usr/lib/libprofiler.so ./app",
    ),
    ("show live disk I/O by process updated every second", "sudo iotop -o -b -n 5 -d 1 | tail -20"),
    ("show per-device disk throughput every 2 seconds", "iostat -x 2 5 | grep -v '^$'"),
    ("watch disk read/write speeds on macOS", "iostat -d -w 2 5"),
    (
        "find which process is hammering disk I/O right now",
        "sudo iotop -o -P -b -n 1 | sort -k10 -rn | head -10",
    ),
    (
        "measure latency of disk operations with fio quick test",
        "fio --name=randread --ioengine=libaio --iodepth=16 --rw=randread --bs=4k --size=256M --runtime=10 --filename=/tmp/fio_test",
    ),
    ("open crontab for editing", "EDITOR=nano crontab -e"),
    (
        "list all cron jobs for the current user",
        "crontab -l 2>/dev/null || echo 'no crontab for $USER'",
    ),
    ("remove all cron jobs for the current user", "crontab -r"),
    (
        "back up current crontab before modifying it",
        "crontab -l > ~/crontab.bak.$(date +%Y%m%d) 2>/dev/null",
    ),
    (
        "schedule a script to run every day at 2:30 AM",
        "(crontab -l 2>/dev/null; echo '30 2 * * * /opt/scripts/daily.sh >> /var/log/daily.log 2>&1') | crontab -",
    ),
    (
        "run a job every 15 minutes and log output",
        "(crontab -l 2>/dev/null; echo '*/15 * * * * /opt/scripts/check.sh >> /var/log/check.log 2>&1') | crontab -",
    ),
    ("enable a systemd service to start on boot", "sudo systemctl enable --now myapp.service"),
    (
        "disable a systemd service and stop it immediately",
        "sudo systemctl disable --now myapp.service",
    ),
    (
        "view the last 100 lines of a service journal",
        "journalctl -u myapp.service -n 100 --no-pager",
    ),
    (
        "create a minimal systemd unit file for a web service",
        "printf '[Unit]\\nDescription=My Application\\nAfter=network.target\\n\\n[Service]\\nUser=appuser\\nWorkingDirectory=/opt/myapp\\nExecStart=/opt/myapp/bin/server\\nRestart=always\\nRestartSec=5\\n\\n[Install]\\nWantedBy=multi-user.target\\n' | sudo tee /etc/systemd/system/myapp.service > /dev/null",
    ),
    (
        "load and start a launchd plist agent immediately",
        "launchctl load -w ~/Library/LaunchAgents/com.example.myapp.plist",
    ),
    (
        "unload and stop a launchd agent",
        "launchctl unload -w ~/Library/LaunchAgents/com.example.myapp.plist",
    ),
    ("check if a launchd agent is running", "launchctl list | grep com.example.myapp"),
    (
        "run a command every 5 minutes via a launchd plist",
        'printf \'<?xml version="1.0" encoding="UTF-8"?>\\n<plist version="1.0"><dict>\\n<key>Label</key><string>com.example.heartbeat</string>\\n<key>ProgramArguments</key><array><string>/opt/scripts/heartbeat.sh</string></array>\\n<key>StartInterval</key><integer>300</integer>\\n<key>RunAtLoad</key><true/>\\n</dict></plist>\' > ~/Library/LaunchAgents/com.example.heartbeat.plist && launchctl load -w ~/Library/LaunchAgents/com.example.heartbeat.plist',
    ),
    (
        "schedule a one-time job to run in 10 minutes",
        "echo '/opt/scripts/reindex.sh >> /tmp/reindex.log 2>&1' | at now + 10 minutes",
    ),
    ("list all pending at jobs", "atq"),
    ("remove a pending at job by job number", "atrm 3"),
    (
        "start a supervisor-managed process and check its status",
        "supervisorctl start myapp && supervisorctl status myapp",
    ),
    ("tail supervisor log for a specific program", "supervisorctl tail -f myapp stderr"),
    (
        "reload supervisor config and restart all programs",
        "supervisorctl reread && supervisorctl update && supervisorctl restart all",
    ),
    ("add a third-party Homebrew tap", "brew tap hashicorp/tap"),
    ("install a GUI application with Homebrew Cask", "brew install --cask visual-studio-code"),
    ("start a Homebrew-managed background service", "brew services start postgresql@16"),
    (
        "stop and remove a Homebrew service from auto-start",
        "brew services stop redis && brew services cleanup",
    ),
    ("remove unused Homebrew downloads and old versions", "brew cleanup --prune=7 -s"),
    ("upgrade all outdated Homebrew packages", "brew update && brew upgrade"),
    ("install dependencies without modifying the lockfile", "npm ci"),
    ("add a dev dependency with pnpm", "pnpm add -D typescript"),
    ("run a package binary without installing it globally", "npx --yes tsx src/seed.ts"),
    ("check which installed npm packages are outdated", "npm outdated --depth=0"),
    ("list top-level npm packages only", "npm ls --depth=0"),
    (
        "create an isolated virtual environment with uv and install deps",
        "uv venv .venv && uv pip install -r requirements.txt",
    ),
    ("install a Python CLI tool globally with pipx", "pipx install httpie"),
    ("upgrade all pipx-installed tools", "pipx upgrade-all"),
    (
        "sync project dependencies precisely from pyproject.toml with uv",
        "uv pip sync requirements/prod.txt",
    ),
    (
        "install a package and its recommended dependencies on Debian",
        "sudo apt-get install -y --install-recommends git-lfs",
    ),
    ("search available packages matching a keyword on Red Hat", "dnf search 'postgresql'"),
    ("show which package provides a specific file on Debian", "dpkg -S /usr/bin/psql"),
    (
        "install a specific Node.js version with nvm and use it",
        "nvm install 22 && nvm use 22 && nvm alias default 22",
    ),
    ("set a global Python version with pyenv", "pyenv install 3.13.0 && pyenv global 3.13.0"),
    (
        "update the stable Rust toolchain and all components",
        "rustup update stable && rustup component add clippy rustfmt",
    ),
    ("show current power management settings", "pmset -g"),
    ("prevent display sleep when on AC power", "sudo pmset -c displaysleep 0"),
    ("set battery-only sleep to 10 minutes", "sudo pmset -b sleep 10"),
    ("show power management assertion reasons why sleep is blocked", "pmset -g assertions"),
    (
        "check what woke the Mac from sleep last time",
        "pmset -g log | grep -E 'Wake|Sleep' | tail -20",
    ),
    (
        "check if a binary is allowed by Gatekeeper",
        "spctl --assess --verbose /Applications/SomeApp.app",
    ),
    ("show code signing details of an application", "codesign -dvv /Applications/SomeApp.app 2>&1"),
    (
        "verify the code signature of a binary is intact",
        "codesign --verify --strict --verbose=2 /usr/local/bin/mytool",
    ),
    (
        "sign a binary with your developer identity",
        "codesign --force --sign 'Developer ID Application: Acme Corp' /path/to/binary",
    ),
    ("show all Gatekeeper rules currently in effect", "spctl --list"),
    (
        "show kernel logs from the last 5 minutes",
        "log show --predicate 'process == \"kernel\"' --last 5m --style compact",
    ),
    (
        "stream live system log filtered to a subsystem",
        "log stream --predicate 'subsystem == \"com.apple.network\"' --level debug",
    ),
    (
        "find recent crashes for a specific process",
        "log show --predicate 'process == \"Safari\" AND messageType == fault' --last 1h",
    ),
    ("list all extended attributes on a file", "xattr -l ~/Downloads/SomeApp.dmg"),
    (
        "remove quarantine flag from a downloaded file",
        "xattr -d com.apple.quarantine ~/Downloads/SomeApp.dmg",
    ),
    (
        "strip all extended attributes from a directory recursively",
        "xattr -cr ~/Downloads/untrusted_folder",
    ),
    ("resize an image to 800px wide preserving aspect ratio", "sips --resampleWidth 800 photo.jpg"),
    (
        "batch convert all PNGs to JPEG in current directory",
        "sips -s format jpeg *.png --out converted/",
    ),
    ("show all metadata for an image file", "mdls photo.jpg"),
    ("start an immediate Time Machine backup", "tmutil startbackup --auto --rotation"),
    ("list all Time Machine snapshot dates", "tmutil listbackups"),
    ("show how much data changed since the last backup", "tmutil compare -n | tail -5"),
    (
        "trim a video from 00:01:30 to 00:04:00 without re-encoding",
        "ffmpeg -ss 00:01:30 -to 00:04:00 -i input.mp4 -c copy trimmed.mp4",
    ),
    (
        "extract audio track from a video as mp3",
        "ffmpeg -i video.mp4 -vn -ar 44100 -ac 2 -b:a 192k audio.mp3",
    ),
    (
        "convert a video to a gif with palette optimization",
        "ffmpeg -i input.mp4 -vf 'fps=15,scale=640:-1:flags=lanczos,palettegen' palette.png && ffmpeg -i input.mp4 -i palette.png -filter_complex 'fps=15,scale=640:-1:flags=lanczos[x];[x][1:v]paletteuse' output.gif",
    ),
    (
        "concatenate multiple mp4 files seamlessly",
        "printf 'file %s\\n' clip1.mp4 clip2.mp4 clip3.mp4 > filelist.txt && ffmpeg -f concat -safe 0 -i filelist.txt -c copy merged.mp4",
    ),
    (
        "extract a single frame from video at timestamp",
        "ffmpeg -ss 00:02:15 -i video.mp4 -frames:v 1 -q:v 2 frame.jpg",
    ),
    (
        "reduce video bitrate for web streaming",
        "ffmpeg -i input.mp4 -vcodec libx264 -crf 28 -preset slow -acodec aac -b:a 128k web.mp4",
    ),
    (
        "add subtitles from srt file to video",
        "ffmpeg -i video.mp4 -vf subtitles=subs.srt output_with_subs.mp4",
    ),
    (
        "convert and compress a TIFF to JPEG with 85 quality",
        "convert input.tiff -quality 85 output.jpg",
    ),
    (
        "batch watermark all images in a directory",
        "mogrify -draw \"text 10,30 'Copyright 2026'\" -font Helvetica -pointsize 20 -fill 'rgba(255,255,255,0.5)' *.jpg",
    ),
    (
        "create a contact sheet thumbnail grid from images",
        "montage *.jpg -geometry 200x150+4+4 -tile 4x contactsheet.jpg",
    ),
    ("strip all EXIF metadata from images in place", "mogrify -strip *.jpg"),
    ("convert wav to mp3 using sox and lame", "sox input.wav -t mp3 output.mp3"),
    ("trim an audio file to keep seconds 30 through 90", "sox input.wav output.wav trim 30 60"),
    ("normalize audio volume to prevent clipping", "sox --norm input.wav normalized.wav"),
    (
        "split audio file on silence for track detection",
        "sox input.wav output.wav silence 1 0.1 0.1% 1 3.0 0.1% : newfile : restart",
    ),
    (
        "download a YouTube video as best quality mp4",
        "yt-dlp -f 'bestvideo[ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]' -o '%(title)s.%(ext)s' 'https://youtu.be/VIDEO_ID'",
    ),
    (
        "extract only audio from a YouTube playlist as mp3",
        "yt-dlp -x --audio-format mp3 --audio-quality 0 -o '%(playlist_index)02d - %(title)s.%(ext)s' 'https://www.youtube.com/playlist?list=PLAYLIST_ID'",
    ),
    (
        "download subtitles for a video without downloading video",
        "yt-dlp --skip-download --write-subs --sub-lang en 'https://youtu.be/VIDEO_ID'",
    ),
    (
        "merge multiple PDFs into one with ghostscript",
        "gs -dBATCH -dNOPAUSE -q -sDEVICE=pdfwrite -sOutputFile=merged.pdf part1.pdf part2.pdf part3.pdf",
    ),
    (
        "extract pages 3 through 7 from a PDF using qpdf",
        "qpdf --empty --pages input.pdf 3-7 -- extracted.pdf",
    ),
    ("split a PDF into one file per page", "qpdf --split-pages input.pdf page_%d.pdf"),
    (
        "extract all IPv4 addresses from a file using PCRE",
        "grep -oP '(?<![0-9])(?:[0-9]{1,3}\\.){3}[0-9]{1,3}(?![0-9])' file.txt | sort -u",
    ),
    ("match lines containing a word boundary with PCRE", "grep -P '\\bfoo\\b' file.txt"),
    (
        "find lines where a number is followed by specific text using lookahead",
        "grep -P '[0-9]+(?= errors found)' build.log",
    ),
    (
        "extract content inside double quotes using named capture",
        'grep -oP \'"(?P<value>[^"]+)"\' config.json | grep -oP \'(?<=")[^"]+(?=")\'',
    ),
    ("match lines that do NOT contain any digit", "grep -P '^[^0-9]+$' file.txt"),
    ("extract function call arguments using PCRE", "grep -oP 'connect\\(\\K[^)]+' db.py"),
    ("replace only the second occurrence of a pattern on each line", "sed 's/foo/bar/2' file.txt"),
    ("delete lines between two inclusive patterns", "sed '/BEGIN/,/END/d' file.txt"),
    ("insert a line before a pattern match", "sed '/^server {/i\\    # managed block' nginx.conf"),
    ("append text after a matching line", "sed '/listen 80/a\\    listen 443 ssl;' nginx.conf"),
    (
        "extract a capture group using sed extended regex",
        "sed -nE 's/.*version[[:space:]]+([0-9.]+).*/\\1/p' Makefile",
    ),
    ("print lines where field 3 is greater than 1000", "awk '$3 > 1000' metrics.txt"),
    ("print lines between pattern start and end inclusive", "awk '/^START$/,/^END$/' logfile.txt"),
    (
        "sum field 2 only for lines matching a pattern",
        "awk '/ERROR/ {sum += $2} END {print sum}' app.log",
    ),
    ("reformat columns rearranging field order", "awk -F',' '{print $3, $1, $2}' OFS='|' data.csv"),
    (
        "in-place replace with perl across multiple files",
        "perl -pi -e 's/old_api_endpoint/new_api_endpoint/g' **/*.ts",
    ),
    (
        "extract and print a named capture group with perl",
        "perl -nE 'say $+{host} if /host=(?<host>[\\w.]+)/' config.txt",
    ),
    (
        "delete lines matching a pattern in-place with perl",
        "perl -ni -e 'print unless /^#/' config.py",
    ),
    (
        "use perl lookahead to match word not followed by suffix",
        "perl -nE 'say if /foo(?!bar)/' file.txt",
    ),
    ("transliterate characters in-place with perl", "perl -pi -e 'tr/a-z/A-Z/' file.txt"),
    (
        "use perl to join continuation lines ending with backslash",
        "perl -0777 -pe 's/\\\\\\n//g' Makefile",
    ),
    (
        "prepend a directory to PATH for the current session only",
        'export PATH="/usr/local/opt/ruby/bin:$PATH"',
    ),
    (
        "add a directory to PATH permanently in zsh",
        "echo 'export PATH=\"$HOME/.local/bin:$PATH\"' >> ~/.zshrc && source ~/.zshrc",
    ),
    (
        "remove a specific entry from PATH without restarting shell",
        "export PATH=$(echo \"$PATH\" | tr ':' '\\n' | grep -v '/usr/local/opt/old' | tr '\\n' ':' | sed 's/:$//')",
    ),
    ("show all directories in PATH one per line", "echo \"$PATH\" | tr ':' '\\n'"),
    ("check which binary in PATH would run for a command", "type -a python3"),
    (
        "define a persistent alias in zsh",
        "echo \"alias ll='ls -lAh --color=auto'\" >> ~/.zshrc && source ~/.zshrc",
    ),
    (
        "define a shell function to make and enter a directory",
        'mkcd() { mkdir -p "$1" && cd "$1"; }',
    ),
    (
        "define a function to activate a python venv if it exists",
        "activate() { [[ -f .venv/bin/activate ]] && source .venv/bin/activate || echo 'no .venv found'; }",
    ),
    ("unset an alias that is shadowing a system command", "unalias ls"),
    ("list all currently defined shell functions", "declare -f"),
    (
        "run cleanup function on script exit regardless of success",
        "trap 'rm -f /tmp/lockfile.$$; echo cleaned up' EXIT",
    ),
    (
        "catch SIGINT in a script and exit gracefully",
        "trap 'echo; echo \"Interrupted — exiting\"; exit 130' INT",
    ),
    ("re-enable default SIGPIPE handling after suppressing it", "trap '' PIPE"),
    (
        "print error line number on any command failure",
        "trap 'echo \"Error at line $LINENO\" >&2' ERR",
    ),
    ("enable strict mode for safer scripting", "set -euo pipefail"),
    ("enable debug tracing to see every command before execution", "set -x"),
    ("disable glob expansion temporarily for a single command", "set -f; cp *.txt /tmp/; set +f"),
    ("turn on extended globbing in zsh", "setopt EXTENDED_GLOB"),
    (
        "search zsh history interactively with fzf",
        "history 0 | fzf --tac --no-sort | awk '{$1=\"\"; print $0}' | xargs",
    ),
    ("append current session history to history file immediately", "history -a"),
    (
        "increase zsh history size and avoid duplicates",
        "echo 'HISTSIZE=100000; SAVEHIST=100000; setopt HIST_IGNORE_ALL_DUPS SHARE_HISTORY' >> ~/.zshrc",
    ),
    ("show the last 20 commands with timestamps in bash", "HISTTIMEFORMAT='%F %T  ' history 20"),
    ("clear the current shell history without touching the file", "history -c"),
    ("re-execute the last command that started with a prefix", "!git"),
    (
        "export a variable so all child processes inherit it",
        "export DATABASE_URL='postgresql://user:pass@localhost:5432/mydb'",
    ),
    ("source a .env file into the current shell safely", "set -a && source .env && set +a"),
    ("list recent GitHub Actions workflow runs", "gh run list --limit 20"),
    (
        "watch a GitHub Actions run in real time",
        "gh run watch $(gh run list --limit 1 --json databaseId -q '.[0].databaseId')",
    ),
    (
        "re-run all failed jobs in the latest workflow run",
        "gh run rerun --failed $(gh run list --limit 1 --json databaseId -q '.[0].databaseId')",
    ),
    (
        "view logs for a specific failed run",
        "gh run view --log-failed $(gh run list --limit 1 --json databaseId -q '.[0].databaseId')",
    ),
    ("list all workflow files in a repo", "gh workflow list"),
    (
        "manually trigger a workflow with an input",
        "gh workflow run deploy.yml -f environment=staging",
    ),
    ("disable a GitHub Actions workflow", "gh workflow disable build.yml"),
    ("initialize terraform and upgrade providers", "terraform init -upgrade"),
    ("plan terraform changes and save to file", "terraform plan -out=tfplan.binary"),
    ("apply a saved terraform plan", "terraform apply tfplan.binary"),
    ("destroy specific terraform resource", "terraform destroy -target=aws_instance.web"),
    ("show current terraform state summary", "terraform state list"),
    (
        "import an existing resource into terraform state",
        "terraform import aws_s3_bucket.assets my-bucket-name",
    ),
    ("format all terraform files in place", "terraform fmt -recursive"),
    ("ping all hosts in inventory", "ansible all -m ping -i inventory.ini"),
    (
        "run ad-hoc shell command on a host group",
        "ansible webservers -m shell -a 'systemctl status nginx' -i inventory.ini",
    ),
    (
        "copy a file to all remote hosts",
        "ansible all -m copy -a 'src=./app.conf dest=/etc/app/app.conf' -i inventory.ini --become",
    ),
    (
        "list all available make targets",
        "make -qp | awk -F':' '/^[a-zA-Z0-9][^$#\\/\\t=]*:([^=]|$)/ {split($1,A,/ /); for(i in A) print A[i]}' | sort -u",
    ),
    ("run just recipe with dry-run to preview commands", "just --dry-run deploy"),
    ("run only tests marked as slow", "pytest -m slow -v"),
    ("run tests matching a keyword expression", "pytest -k 'auth and not admin' -v"),
    (
        "run a single test function by node ID",
        "pytest tests/test_api.py::test_login_returns_token -v",
    ),
    ("run tests in parallel across 4 workers", "pytest -n 4"),
    ("show the 10 slowest tests after a run", "pytest --durations=10"),
    ("stop on first failure and enter debugger", "pytest -x --pdb"),
    ("regenerate all pytest snapshots", "pytest --snapshot-update"),
    ("run tests and emit junit XML for CI", "pytest --junitxml=test-results.xml"),
    (
        "run tests with coverage and show missing lines",
        "pytest --cov=src --cov-report=term-missing",
    ),
    ("fail the build if coverage drops below 80%", "pytest --cov=src --cov-fail-under=80"),
    (
        "generate an HTML coverage report",
        "pytest --cov=src --cov-report=html && open htmlcov/index.html",
    ),
    (
        "show coverage diff against main branch",
        "coverage run -m pytest && coverage xml && diff-cover coverage.xml --compare-branch=main",
    ),
    ("run ruff with auto-fix on entire project", "ruff check . --fix"),
    (
        "run eslint on staged files only",
        "git diff --cached --name-only --diff-filter=ACM | grep '\\.ts$' | xargs eslint",
    ),
    (
        "run clippy on all targets treating warnings as errors",
        "cargo clippy --all-targets -- -D warnings",
    ),
    (
        "lint all Python files and show first error only",
        "ruff check . --select E,W --quiet | head -1",
    ),
    (
        "check types across the whole monorepo with pyright",
        "pyright --outputjson 2>/dev/null | jq '.summary'",
    ),
    ("run mypy in strict mode on a module", "mypy --strict src/auth.py"),
    (
        "run criterion benchmarks and open HTML report",
        "cargo bench && open target/criterion/report/index.html",
    ),
    (
        "compare benchmark results against baseline",
        "hyperfine --warmup 5 --export-markdown bench.md './cmd_old' './cmd_new'",
    ),
    ("show column names and types of a CSV file", "csvstat --names data.csv"),
    (
        "filter CSV rows where column value exceeds threshold",
        "csvgrep -c revenue -m '' data.csv | csvsort -c revenue -r | head -20",
    ),
    ("join two CSV files on a shared column", "csvjoin -c id users.csv orders.csv"),
    ("convert CSV to JSON array", "csvjson data.csv"),
    ("count rows in a CSV excluding header", "csvstat -c 1 --count data.csv | tail -1"),
    ("flatten nested JSON array and extract unique values", "jq '[.[].tags[]] | unique' data.json"),
    (
        "group JSON array by a field and count",
        "jq 'group_by(.status) | map({status: .[0].status, count: length})' records.json",
    ),
    (
        "transform JSON with conditional field renaming",
        "jq '[.[] | {id, name: (.fullName // .name), active: (.status == \"enabled\")}]' users.json",
    ),
    (
        "merge JSON objects from two files at the key level",
        "jq -n --slurpfile a a.json --slurpfile b b.json '$a[0] * $b[0]'",
    ),
    (
        "extract nested paths that match a pattern",
        'jq \'.. | strings | select(test("error"; "i"))\' response.json',
    ),
    ("read a nested YAML value by path", "yq '.spec.replicas' deployment.yaml"),
    ("set a YAML field in place", "yq -i '.spec.replicas = 3' deployment.yaml"),
    (
        "merge two YAML files, second overrides first",
        "yq eval-all 'select(fileIndex == 0) * select(fileIndex == 1)' base.yaml override.yaml",
    ),
    ("convert a YAML file to JSON", "yq -o=json config.yaml"),
    ("get summary statistics for all columns with xsv", "xsv stats data.csv | xsv table"),
    ("sort a large CSV by a numeric column descending", "xsv sort -s revenue -R data.csv"),
    ("select specific columns from a CSV with xsv", "xsv select id,name,email data.csv"),
    (
        "convert JSON to YAML using python",
        'python3 -c "import sys, json, yaml; yaml.dump(json.load(sys.stdin), sys.stdout, default_flow_style=False)" < data.json',
    ),
    ("base64 encode a file and copy to clipboard", "base64 < secret.key | tr -d '\\n' | pbcopy"),
    (
        "base64 decode a string and write to file",
        "echo 'SGVsbG8gV29ybGQ=' | base64 --decode > output.txt",
    ),
    (
        "capture packets on port 443 and write to pcap file",
        "tcpdump -i eth0 -n 'tcp port 443' -w capture.pcap",
    ),
    (
        "capture DNS queries and show hostnames",
        "tcpdump -i any -n 'udp port 53' -l 2>/dev/null | grep -oP 'A\\? \\K[^ ]+'",
    ),
    (
        "watch HTTP POST requests in real time",
        "tcpdump -i eth0 -A -s 0 'tcp port 80 and (tcp[((tcp[12:1] & 0xf0) >> 2):4] = 0x504f5354)' 2>/dev/null",
    ),
    (
        "capture packets between two specific hosts",
        "tcpdump -i eth0 -n 'host 10.0.0.1 and host 10.0.0.2' -w host-pair.pcap",
    ),
    (
        "allow established and related connections in iptables",
        "iptables -A INPUT -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT",
    ),
    (
        "rate-limit incoming SSH connections",
        "iptables -A INPUT -p tcp --dport 22 -m conntrack --ctstate NEW -m limit --limit 3/min --limit-burst 3 -j ACCEPT",
    ),
    ("list nftables ruleset", "nft list ruleset"),
    (
        "block outgoing traffic to a specific IP with nftables",
        "nft add rule ip filter output ip daddr 203.0.113.0/24 drop",
    ),
    ("query MX records for a domain", "dig MX example.com +short"),
    ("check DNSSEC validation for a domain", "dig +dnssec example.com"),
    ("trace the full DNS resolution chain", "dig +trace example.com"),
    ("query all DNS record types for a domain", "dig ANY example.com @8.8.8.8"),
    (
        "measure full HTTP request timing breakdown",
        "curl -so /dev/null -w 'namelookup:%{time_namelookup}s connect:%{time_connect}s starttransfer:%{time_starttransfer}s total:%{time_total}s\\n' https://example.com",
    ),
    (
        "check which TLS version and cipher a server uses",
        "curl -svo /dev/null https://example.com 2>&1 | grep -E 'SSL|TLS|cipher'",
    ),
    (
        "send request with custom Host header for vhost testing",
        "curl -sf -H 'Host: staging.example.com' http://10.0.0.5/healthz",
    ),
    (
        "follow redirects and print each redirect URL",
        "curl -sIL https://short.link/abc 2>&1 | grep -i 'location:'",
    ),
    ("run iperf3 TCP throughput test to a server", "iperf3 -c 192.168.1.10 -t 10 -P 4"),
    ("run iperf3 UDP bandwidth test at 100 Mbps", "iperf3 -c 192.168.1.10 -u -b 100M -t 10"),
    (
        "run mtr in report mode and show 100 cycles",
        "mtr --report --report-cycles 100 --no-dns 8.8.8.8",
    ),
    (
        "traceroute using TCP SYN instead of UDP for firewalled paths",
        "traceroute -T -p 443 example.com",
    ),
    ("start the dev server with bun", "bun run dev"),
    ("run the tests with bun", "bun test"),
    ("run bun tests and rerun on file change", "bun test --watch --bail"),
    ("build the project with bun", "bun run build"),
    ("install all the dependencies with bun", "bun install"),
    ("add a package with bun", "bun add zod"),
    ("remove a package with bun", "bun remove lodash"),
    ("add a dev dependency with bun", "bun add -d @types/node"),
    ("run a script from package json with bun", "bun run lint"),
    ("upgrade all bun dependencies", "bun update"),
    ("check what bun version I have", "bun --version"),
    ("run a single test file with bun", "bun test src/auth.test.ts"),
    ("start the dev server", "npm run dev"),
    ("run the tests", "npm test"),
    ("build the project", "npm run build"),
    ("check for type errors", "npx tsc --noEmit"),
    ("install the dependencies", "npm install"),
    ("what scripts are available", "npm run"),
    ("lint and fix the code", "npm run lint -- --fix"),
    ("update all dependencies", "npm update"),
    ("add typescript as a dev dependency", "npm install -D typescript"),
    ("run just the failing tests", "npm test -- --bail"),
    ("check for security vulnerabilities", "npm audit"),
    ("install packages with pnpm", "pnpm install"),
    ("add a package with pnpm", "pnpm add express"),
    ("run dev with pnpm", "pnpm dev"),
    ("run cargo tests", "cargo test"),
    ("check for Rust warnings", "cargo clippy --all-targets"),
    ("build the Rust project", "cargo build"),
    ("build Rust in release mode", "cargo build --release"),
    ("run the Rust project", "cargo run"),
    ("what's running on port 3000", "lsof -ti:3000"),
    ("what's using port 8080", "lsof -nP -iTCP:8080 -sTCP:LISTEN"),
    ("kill whatever is on port 3000", "fuser -k 3000/tcp"),
    ("show me what's eating memory", "ps aux --sort=-%mem | head -10"),
    ("show me what's using the most CPU", "ps aux --sort=-%cpu | head -10"),
    ("how much disk space do I have left", "df -h /"),
    ("how long has the system been running", "uptime"),
    ("what's my IP address", "curl -s ifconfig.me"),
    ("am I connected to the internet", "ping -c1 8.8.8.8 >/dev/null 2>&1 && echo yes || echo no"),
    ("show me the wifi network I'm on", "networksetup -getairportnetwork en0"),
    ("what branch am I on", "git branch --show-current"),
    ("what changed since yesterday", "git log --since='yesterday' --oneline"),
    ("who last touched this file", "git log -1 --format='%an %ar' -- README.md"),
    ("show me what I've changed", "git diff"),
    ("show me what's staged", "git diff --name-only --cached"),
    ("what files did I change", "git status --short"),
    ("undo my last commit but keep the changes", "git reset --soft HEAD~1 --quiet"),
    ("push my current branch up", "git push --set-upstream origin HEAD"),
    ("sync my branch with the latest from main", "git fetch origin && git rebase origin/main"),
    ("stash what I'm working on", "git stash push -m 'wip'"),
    ("pop my stash back", "git stash pop"),
    ("pop this folder open in Finder", "open -a Finder ."),
    ("copy that to my clipboard", "pbcopy"),
    ("what version of node am I using", "node --version"),
    ("what version of Python is installed", "python3 --version"),
    ("show me the last few commands I ran", "history | tail -20"),
    ("reload my shell config", "exec zsh"),
    ("open the current directory in VS Code", "code ."),
    ("show me what containers are running", "docker ps"),
    ("start up the docker compose stack", "docker compose up -d"),
    ("bring down the docker compose stack", "docker compose down"),
    ("check the logs for the web container", "docker compose logs -f --tail 50 web"),
    ("check the logs for the database container", "docker logs -f --tail 50 postgres"),
    ("restart the web container", "docker compose restart web"),
    ("get a shell inside the container", "docker exec -it web /bin/sh"),
    ("rebuild and restart the containers", "docker compose up -d --build"),
    ("how much space are my docker images taking up", "docker system df"),
    ("clean up all the docker stuff I don't need", "docker system prune -af --volumes"),
    ("pull the latest images", "docker compose pull"),
    ("stop all the running containers", "docker compose stop"),
    (
        "show me which containers crashed recently",
        "docker ps -a --filter 'status=exited' --format 'table {{.Names}}\\t{{.Status}}'",
    ),
    ("show me the environment variables in the container", "docker exec web env | sort"),
    ("force recreate all the containers", "docker compose up -d --force-recreate"),
    ("what tasks are available", "just --list"),
    ("run the deploy task", "just deploy"),
    ("run tests in watch mode", "just test-watch"),
    ("format all the code", "just fmt"),
    ("run the build task", "just build"),
    ("run the lint task", "just lint"),
    ("run the setup task", "just setup"),
    ("run the dev task", "just dev"),
    ("run the clean task", "just clean"),
    ("run the release task", "just release"),
    ("preview what a recipe does without running it", "just --dry-run build"),
    ("show me the source of a just recipe", "just --show dev"),
    ("check system stats", "btop"),
    ("show CPU usage", "top -l 1 | head -5"),
    ("show memory pressure", "memory_pressure"),
    ("what processes are using the most CPU", "ps aux -r | head -10"),
    ("check battery status", "pmset -g batt"),
    ("show thermal throttling", "pmset -g therm"),
    ("check disk health", "diskutil info disk0 | grep -i 'smart\\|status'"),
    ("how hot is my Mac", "sudo powermetrics --samplers smc -i1 -n1 2>/dev/null | grep -i temp"),
    ("show network bandwidth usage", "nettop -P -L 1 -t wifi"),
    ("what's connected via USB", "system_profiler SPUSBDataType"),
    ("show all listening ports", "lsof -i -P | grep LISTEN"),
    ("how much RAM do I have free", "vm_stat | grep -E 'Pages free|Pages inactive'"),
    ("is my SSD healthy", "smartctl -a disk0 2>/dev/null || diskutil info disk0 | grep SMART"),
    ("what's eating my disk space", "du -sh ~/* 2>/dev/null | sort -rh | head -10"),
    ("show me running processes", "ps aux | head -20"),
    (
        "what's my CPU temperature right now",
        "sudo powermetrics --samplers smc -i1 -n1 2>/dev/null | grep 'CPU die'",
    ),
    (
        "show GPU memory usage",
        "sudo powermetrics --samplers gpu_power -i1 -n1 2>/dev/null | grep -i gpu",
    ),
    ("how fast is my internet", "networkQuality"),
    ("show me disk read and write speeds", "iostat -d disk0 1 3"),
    ("what's using my network right now", "lsof -i | grep ESTABLISHED | head -20"),
    (
        "show memory usage by app",
        "ps aux --sort=-%mem | awk 'NR<=11{print $4\"% \"$11}' | column -t",
    ),
    (
        "monitor live CPU per core",
        "sudo powermetrics --samplers cpu_power -i1000 -n3 2>/dev/null | grep -E 'CPU|%'",
    ),
    (
        "what's my Mac's model and specs",
        "system_profiler SPHardwareDataType | grep -E 'Model|Memory|Processor'",
    ),
    ("install ripgrep", "brew install ripgrep"),
    ("what's outdated", "brew outdated"),
    ("install a cask app", "brew install --cask rectangle"),
    ("search for a package", "brew search terminal"),
    ("remove a package", "brew uninstall package-name"),
    ("show what I have installed", "brew list"),
    ("install a global npm tool", "npm install -g package-name"),
    ("install with cargo", "cargo install tool-name"),
    ("update rust toolchain", "rustup update"),
    ("install a python tool globally", "pipx install tool-name"),
    ("what npm packages are outdated globally", "npm outdated -g"),
    (
        "upgrade all pip packages",
        "pip list --outdated --format=json | python3 -c \"import json,sys; [print(p['name']) for p in json.load(sys.stdin)]\" | xargs pip install -U",
    ),
    ("show me what brew services are running", "brew services list"),
    ("restart a brew service", "brew services restart postgresql@16"),
    (
        "check if a formula is installed",
        "brew list ripgrep 2>/dev/null && echo installed || echo not installed",
    ),
    ("uninstall a cask app", "brew uninstall --cask app-name"),
    ("add a new brew tap", "brew tap homebrew/cask-fonts"),
    ("show brew doctor warnings", "brew doctor"),
    ("install bun", "brew install oven-sh/bun/bun"),
    ("update bun", "bun upgrade"),
    ("list globally installed npm packages", "npm list -g --depth=0"),
    ("go to my projects folder", "cd ~/Projects"),
    ("jump to cloudagi", "z cloudagi"),
    ("show me the file tree", "eza --icons --tree --level=2"),
    ("find all typescript files", "fd -e ts"),
    ("search for TODO in the code", "rg 'TODO|FIXME' --type ts"),
    ("how big is this directory", "du -sh ."),
    ("show hidden files", "eza -la --icons"),
    ("preview this markdown file", "glow README.md"),
    ("list only directories", "eza -D --icons"),
    ("copy a file", "cp source.txt destination.txt"),
    ("move a file to another folder", "mv file.txt ~/Documents/"),
    ("delete this file", "rm file.txt"),
    ("create a new folder", "mkdir my-new-folder"),
    ("rename a file", "mv oldname.txt newname.txt"),
    ("show the most recently changed files", "eza -la --sort=modified --icons | tail -10"),
    ("find a file by name", "fd config.json"),
    ("count how many files are in this folder", "fd -t f | wc -l"),
    ("open current folder in Finder", "open ."),
    ("show file sizes in a directory", "eza -l --sort=size --icons"),
    ("commit everything with a message", "git add -A && git commit -m 'your message here'"),
    ("push my changes", "git push"),
    ("pull the latest", "git pull"),
    ("create a new branch", "git checkout -b feature/name"),
    ("switch to main", "git checkout main"),
    ("show recent commits", "git log --oneline -10"),
    ("stash my changes", "git stash"),
    ("undo the last commit but keep changes", "git reset --soft HEAD~1"),
    ("check the status", "git status"),
    ("show what changed in the last commit", "git show --stat HEAD"),
    (
        "pull down a remote branch",
        "git fetch origin && git checkout -b feature/name origin/feature/name",
    ),
    ("delete a local branch", "git branch -d feature/old-branch"),
    ("see who wrote this code", "git blame src/main.ts"),
    ("find when a bug was introduced", "git log --oneline --all | head -20"),
    ("sync my fork with upstream", "git fetch upstream && git rebase upstream/main"),
    ("discard my changes to a file", "git checkout -- src/file.ts"),
    ("tag the current commit", "git tag -a v1.0.0 -m 'release v1.0.0'"),
    ("push all tags", "git push --tags"),
    ("show all branches", "git branch -a"),
    ("ask claude to review this code", "claude 'review this code for bugs'"),
    ("start claude in plan mode", "claude --plan"),
    ("start claude without permission prompts", "claude --dangerously-skip-permissions"),
    ("open a fresh claude session with no context", "claude --no-auto-approve"),
    ("ask claude to explain the current directory", "claude 'explain what this project does'"),
    ("have claude write tests for this file", "claude 'write unit tests for src/auth.ts'"),
    ("ask claude to fix the failing test", "claude 'fix the failing test in tests/api.test.ts'"),
    ("ask claude to summarize the last commit", "claude 'summarize the changes in HEAD'"),
    ("continue the last claude conversation", "claude --continue"),
    ("run claude in verbose mode", "claude --verbose"),
    ("ask amp to fix this bug", "amp 'fix the failing test'"),
    ("check amp credits remaining", "amp usage"),
    ("start amp with a specific task", "amp 'implement pagination for the users endpoint'"),
    (
        "ask amp to review the pull request",
        "amp 'review the open pull request for security issues'",
    ),
    ("run amp and open a new chat", "amp"),
    ("run codex in safe mode", "codex --sandbox read-only 'explain this function'"),
    ("run codex review on the last commit", "codex review HEAD~1..HEAD"),
    (
        "ask codex to refactor this module",
        "codex 'refactor src/database.ts to use connection pooling'",
    ),
    (
        "start codex with full auto approval",
        "codex --approval-mode full-auto 'add error handling to all API routes'",
    ),
    (
        "ask codex to explain this codebase",
        "codex 'give me an overview of the project architecture'",
    ),
    ("ask gemini about the architecture", "gemini 'what is the architecture of this project'"),
    ("run gemini with a prompt file", "gemini -p prompt.txt"),
    ("ask gemini to compare two approaches", "gemini 'compare REST vs GraphQL for this API'"),
    ("start cursor agent", "agent"),
    ("ask opencode to implement a feature", "opencode 'add dark mode toggle to the dashboard'"),
    ("run kiro on this project", "kiro"),
    ("ask all agents for opinions", "council 'best approach for caching this dataset'"),
    (
        "get a council decision on the architecture",
        "council 'should we use Redis or an in-memory cache here'",
    ),
    (
        "deploy to Cloud Run from source",
        "gcloud run deploy cloudagi --source . --region us-central1 --allow-unauthenticated",
    ),
    (
        "check Cloud Run logs for my service",
        "gcloud run services logs read cloudagi --region us-central1 --limit 50",
    ),
    ("list my gcloud projects", "gcloud projects list"),
    ("switch gcloud project", "gcloud config set project my-project-id"),
    ("show the active gcloud configuration", "gcloud config list"),
    (
        "authenticate gcloud with application default credentials",
        "gcloud auth application-default login",
    ),
    ("describe a Cloud Run service", "gcloud run services describe cloudagi --region us-central1"),
    (
        "update Cloud Run traffic to the latest revision",
        "gcloud run services update-traffic cloudagi --to-latest --region us-central1",
    ),
    (
        "list Cloud Run revisions",
        "gcloud run revisions list --service cloudagi --region us-central1",
    ),
    (
        "build and push a container image to Artifact Registry",
        "gcloud builds submit --tag gcr.io/my-project/myapp:latest .",
    ),
    ("start supabase locally", "supabase start"),
    ("check supabase status", "supabase status"),
    ("stop supabase local instance", "supabase stop"),
    ("run supabase migrations", "supabase db push"),
    ("open supabase studio in the browser", "supabase studio"),
    (
        "generate supabase typescript types",
        "supabase gen types typescript --local > src/types/supabase.ts",
    ),
    ("push to netlify production", "netlify deploy --prod"),
    ("preview a netlify deployment", "netlify deploy"),
    ("check netlify deploy status", "netlify status"),
    ("open the netlify admin dashboard", "netlify open"),
    ("connect to my tailnet", "tailscale up"),
    ("check tailscale status", "tailscale status"),
    ("connect to ground control", "ssh -t ground-control.online"),
    (
        "start a tmux session on the remote server",
        "ssh -t ground-control.online 'tmux attach -t main 2>/dev/null || tmux new -s main'",
    ),
    (
        "open a remote shell in my main tmux session",
        "ssh -t ground-control.online 'tmux new-window'",
    ),
    (
        "run a command on the remote server without staying connected",
        "ssh ground-control.online 'df -h && free -m'",
    ),
    ("check what is running on the server", "ssh ground-control.online 'ps aux | head -20'"),
    (
        "tail the app logs on the remote server",
        "ssh ground-control.online 'tail -f /var/log/app/app.log'",
    ),
    ("copy a file to the remote server", "scp file.txt arya@ground-control.online:~/"),
    ("copy a file from the server to local", "scp arya@ground-control.online:~/output.csv ./"),
    (
        "sync my project to the server excluding node_modules",
        "rsync -avz --exclude node_modules --exclude .git ./ arya@ground-control.online:~/project/",
    ),
    (
        "sync server logs to local for analysis",
        "rsync -avz arya@ground-control.online:/var/log/app/ ./logs/",
    ),
    (
        "dry run rsync to preview what would be transferred",
        "rsync -avzn --exclude node_modules ./ arya@ground-control.online:~/project/",
    ),
    (
        "expose local port to internet with cloudflared",
        "cloudflared tunnel --url http://localhost:3000",
    ),
    (
        "expose local development server on port 8080",
        "cloudflared tunnel --url http://localhost:8080",
    ),
    ("list all tmux sessions", "tmux ls"),
    ("start a new named tmux session", "tmux new -s work"),
    ("attach to the main tmux session", "tmux attach -t main"),
    ("detach from tmux", "tmux detach"),
    ("split the current tmux pane vertically", "tmux split-window -h"),
    ("split the current tmux pane horizontally", "tmux split-window -v"),
    ("kill a tmux session by name", "tmux kill-session -t old-session"),
    ("start ollama server", "ollama serve"),
    ("run a local llama model", "ollama run llama3.2"),
    ("run the nl2shell model locally", "ollama run hf.co/AryaYT/nl2shell-0.8b"),
    ("run qwen locally for coding tasks", "ollama run qwen2.5-coder:7b"),
    (
        "run a model and pass a prompt directly",
        "ollama run llama3.2 'explain what this error means'",
    ),
    ("list all installed ollama models", "ollama list"),
    ("pull a new model to ollama", "ollama pull qwen2.5:7b"),
    ("pull the latest mistral model", "ollama pull mistral"),
    ("show which ollama models are currently loaded in memory", "ollama ps"),
    ("remove an ollama model to free disk space", "ollama rm llama3.1"),
    ("check ollama version", "ollama version"),
    ("stop the ollama server process", "pkill ollama"),
    ("copy a model to a new name in ollama", "ollama cp llama3.2 my-custom-llama"),
    ("push a local ollama model to a registry", "ollama push my-org/my-model"),
    ("show details about an installed model", "ollama show llama3.2"),
    (
        "show only the name and image of each docker container",
        "docker ps --format '{{.Names}}	{{.Image}}'",
    ),
    (
        "show only the name and status of docker containers",
        "docker ps --format '{{.Names}}	{{.Status}}'",
    ),
    (
        "get the IP address of a docker container",
        "docker inspect mycontainer | jq -r '.[0].NetworkSettings.IPAddress'",
    ),
    (
        "get the environment variables of a docker container",
        "docker inspect mycontainer | jq -r '.[0].Config.Env[]'",
    ),
    (
        "show pod names and their status from kubectl",
        "kubectl get pods -o json | jq -r '.items[] | [.metadata.name, .status.phase] | @tsv'",
    ),
    (
        "get just the cluster server URL from kubeconfig",
        "kubectl config view --minify -o jsonpath='{.clusters[0].cluster.server}'",
    ),
    (
        "show only failed GitHub Actions runs",
        "gh run list --limit 20 --json status,name | jq -r '.[] | select(.status==\"failure\") | .name'",
    ),
    ("get the latest npm version of a package", "npm view react version"),
    (
        "pull the access_token from a curl oauth response",
        "curl -s https://api.example.com/token -d 'grant_type=client_credentials' | jq -r '.access_token'",
    ),
    ("list all keys in a JSON file", "jq 'keys' config.json"),
    ("flatten a nested JSON array to one value per line", "jq -r '.results[].name' data.json"),
    (
        "extract image names from a docker-compose config",
        "docker-compose config | yq '.services[].image' | sort -u",
    ),
    ("show only the PID and command name from ps", "ps aux | awk '{print $2, $11}'"),
    ("show only filesystem name and percent used from df", "df -h | awk 'NR>1 {print $1, $5}'"),
    (
        "show only open files and their PIDs from lsof on port 3000",
        "lsof -i :3000 | awk 'NR>1 {print $2, $1}'",
    ),
    ("show only the second column from a CSV file", "cut -d, -f2 data.csv"),
    (
        "extract the third field from a colon-delimited file",
        "cut -d: -f3 /etc/passwd | sort -n | head -20",
    ),
    ("show unique usernames from the passwd file", "cut -d: -f1 /etc/passwd | sort"),
    ("show error lines with 2 lines of context before them", "grep -B2 'ERROR' app.log | tail -30"),
    (
        "show fatal log lines with 3 lines of surrounding context",
        "grep -C3 'FATAL' /var/log/syslog | tail -40",
    ),
    ("highlight fix commits in git log", "git log --oneline | grep --color=always 'fix'"),
    ("find panic lines with 1 line of surrounding context", "rg -C1 'panic' server.log | tail -20"),
    (
        "extract just the version number from a package.json",
        'sed -n \'s/.*"version": "\\(.*\\)".*/\\1/p\' package.json',
    ),
    ("pull out all URLs from an HTML file", "grep -oE 'https?://[^\"]+' index.html | sort -u"),
    (
        "show only non-comment non-blank lines from a config file",
        "grep -v '^[[:space:]]*#' /etc/ssh/sshd_config | grep -v '^$'",
    ),
    (
        "show the 10 largest directories in the current folder",
        "du -sh */ 2>/dev/null | sort -rh | head -10",
    ),
    ("show the 5 biggest items here", "du -sh * 2>/dev/null | sort -rh | head -5"),
    (
        "show the largest files anywhere under this directory",
        "find . -type f -print0 | xargs -0 du -sh | sort -rh | head -15",
    ),
    ("find the biggest files in my home directory", "du -ah ~ 2>/dev/null | sort -rh | head -10"),
    ("show disk usage by top-level folder sorted by size", "du -sh ~/* 2>/dev/null | sort -rh"),
    ("show the 10 most recently modified files", "ls -lt | head -11"),
    ("show the newest file in this directory", "ls -t | head -1"),
    ("show the 5 oldest files in this directory", "ls -ltr | head -6"),
    ("show the largest files in the current directory", "ls -lSh | head -10"),
    ("show the top 10 memory-hungry processes", "ps aux --sort=-%mem | head -11"),
    ("show the top 5 CPU-consuming processes", "ps aux --sort=-%cpu | head -6"),
    ("show only processes using more than 1 percent CPU", "ps aux | awk '$3 > 1.0' | sort -k3 -rn"),
    ("which Python file has the most lines", "wc -l **/*.py | sort -rn | head -5"),
    (
        "count lines in all TypeScript files and rank them",
        "find . -name '*.ts' | xargs wc -l | sort -rn | head -10",
    ),
    ("which test file is the longest", "wc -l tests/**/*.test.ts 2>/dev/null | sort -rn | head -5"),
    ("show top 5 largest log files", "ls -lSh /var/log/*.log 2>/dev/null | head -5"),
    (
        "show the most common log levels in a log file",
        "awk '{print $3}' app.log | sort | uniq -c | sort -rn",
    ),
    (
        "find the most frequently occurring IP addresses in a log",
        "awk '{print $1}' access.log | sort | uniq -c | sort -rn | head -10",
    ),
    (
        "show which error messages appear most often",
        "grep 'ERROR' app.log | awk -F'ERROR' '{print $2}' | sort | uniq -c | sort -rn | head -10",
    ),
    (
        "show the top 10 git files touched most often",
        "git log --name-only --pretty='' | grep -v '^$' | sort | uniq -c | sort -rn | head -10",
    ),
    ("show environment variables in aligned columns", "env | sort | column -t -s="),
    ("display a CSV file as aligned columns in the terminal", "column -t -s, data.csv | head -20"),
    ("show /etc/passwd as a readable table", "column -t -s: /etc/passwd | head -20"),
    ("align ps output into clean columns", "ps aux | column -t | head -20"),
    (
        "show git log as one line per commit with dates",
        "git log --format='%h %ad %s' --date=short -20",
    ),
    ("show compact git log with author and relative date", "git log --format='%h %ar %an: %s' -15"),
    ("show just the commit hashes from git log", "git log --format='%H' -10"),
    ("show git log with branch graph compact", "git log --oneline --graph --decorate -20"),
    (
        "show only the files changed in the last 5 commits",
        "git log --name-only --pretty='' -5 | grep -v '^$' | sort -u",
    ),
    ("show commits grouped by author", "git shortlog -sn --no-merges | head -10"),
    (
        "show docker images with just name and size",
        "docker images --format '{{.Repository}}:{{.Tag}}	{{.Size}}'",
    ),
    (
        "list kubernetes pods with just name, status, and node",
        "kubectl get pods -o custom-columns='NAME:.metadata.name,STATUS:.status.phase,NODE:.spec.nodeName'",
    ),
    ("show file size in bytes only", "stat -f '%z' myfile.txt"),
    ("show file modification time only", "stat -f '%Sm' -t '%Y-%m-%d %H:%M' myfile.txt"),
    (
        "show df output with aligned columns and human sizes",
        "df -h | awk 'NR==1 || /^\\//' | column -t",
    ),
    (
        "show network interface names and their IPs only",
        "ifconfig | awk '/^[a-z]/{iface=$1} /inet /{print iface, $2}' | column -t",
    ),
    (
        "print a summary table of file extensions and counts",
        "find . -type f | sed 's/.*\\.//' | sort | uniq -c | sort -rn | awk '{printf \"%-6s %s\\n\", $1, $2}' | head -15",
    ),
    ("show load average compact", "uptime | awk -F'load averages:' '{print \"Load:\", $2}'"),
    (
        "show memory usage as a one-liner on macOS",
        "vm_stat | awk '/free/ {free=$3} /active/ {act=$3} END {printf \"Free: %.1fGB  Active: %.1fGB\\n\", free*4096/1e9, act*4096/1e9}'",
    ),
    (
        "show running container names on one comma-separated line",
        "docker ps --format '{{.Names}}' | paste -sd, -",
    ),
    ("count lines in a file", "wc -l < myfile.txt"),
    ("count how many Python files are in this project", "find . -name '*.py' | wc -l"),
    ("count the number of functions in a Python file", "grep -c '^def ' module.py"),
    (
        "count total lines of TypeScript across the project",
        "find . -name '*.ts' -not -path '*/node_modules/*' | xargs wc -l | tail -1",
    ),
    ("how much space does node_modules take", "du -sh node_modules"),
    ("how big is my home directory", "du -sh ~"),
    ("show disk usage summary for each top-level project folder", "du -sh ~/Projects/* | sort -rh"),
    ("count how many test files exist", "find . -name '*.test.ts' | wc -l"),
    (
        "count all JSON files in the project excluding node_modules",
        "find . -name '*.json' -not -path '*/node_modules/*' | wc -l",
    ),
    ("show commit counts by author", "git shortlog -sn --no-merges"),
    (
        "show how many commits each person made this month",
        "git shortlog -sn --no-merges --since='1 month ago'",
    ),
    (
        "show the most common HTTP status codes in an access log",
        "awk '{print $9}' access.log | sort | uniq -c | sort -rn",
    ),
    (
        "count how many times each test file was changed in git",
        "git log --name-only --pretty='' | grep '\\.test\\.' | sort | uniq -c | sort -rn | head -10",
    ),
    (
        "count open GitHub issues by label",
        "gh issue list --limit 200 --json labels | jq '[.[].labels[].name] | group_by(.) | map({label: .[0], count: length}) | sort_by(-.count)[]'",
    ),
    (
        "show how many lines each contributor added in git",
        "git log --numstat --pretty='' | awk '{add+=$1} END {print \"Lines added:\", add}'",
    ),
    ("check if a port is open quietly", "nc -z -w2 localhost 5432 && echo open || echo closed"),
    ("run curl silently and just show the response body", "curl -s https://api.github.com/zen"),
    (
        "check if a brew package is installed without extra output",
        "brew list --formula | grep -q '^ripgrep$' && echo installed || echo missing",
    ),
    ("run make and suppress all error output", "make build 2>/dev/null"),
    (
        "suppress permission errors when searching files",
        "find / -name '*.conf' 2>/dev/null | head -20",
    ),
    (
        "check if a command exists without any output",
        "command -v docker &>/dev/null && echo yes || echo no",
    ),
    ("find yaml files in /etc ignoring permission errors", "find /etc -name '*.yaml' 2>/dev/null"),
    ("show df output without the header line", "df -h | tail -n +2"),
    (
        "show ps output without the header sorted by memory",
        "ps aux | tail -n +2 | sort -k4 -rn | head -10",
    ),
    (
        "strip the header row from a CSV before processing",
        "tail -n +2 data.csv | cut -d, -f1,3 | sort",
    ),
    (
        "quick system summary on macOS",
        "echo \"CPU: $(sysctl -n hw.ncpu) cores  RAM: $(sysctl -n hw.memsize | awk '{printf \"%.0fGB\", $1/1073741824}')  Disk: $(df -h / | awk 'NR==2{print $5}') used  Load: $(sysctl -n vm.loadavg | awk '{print $2}')\"",
    ),
    (
        "show a compact project health summary",
        "echo \"Tests: $(find . -name '*.test.ts' | wc -l | tr -d ' ')  TS files: $(find . -name '*.ts' -not -path '*/node_modules/*' | wc -l | tr -d ' ')  LOC: $(find . -name '*.ts' -not -path '*/node_modules/*' | xargs wc -l 2>/dev/null | tail -1 | awk '{print $1}')\"",
    ),
    (
        "show a compact git repo status",
        "echo \"Branch: $(git branch --show-current)  Commits: $(git rev-list --count HEAD)  Dirty: $(git status --porcelain | wc -l | tr -d ' ') files\"",
    ),
    (
        "quick docker status summary",
        "echo \"Running: $(docker ps -q | wc -l | tr -d ' ')  Stopped: $(docker ps -qa --filter status=exited | wc -l | tr -d ' ')  Images: $(docker images -q | wc -l | tr -d ' ')\"",
    ),
    (
        "show my external and internal IP on one line",
        'echo "External: $(curl -s ifconfig.me)  Internal: $(ipconfig getifaddr en0)"',
    ),
    (
        "compact node project info",
        "node -e \"const p=require('./package.json'); console.log(p.name+'@'+p.version, '| node:'+process.version)\"",
    ),
    (
        "show a one-line process and memory snapshot",
        "ps aux | awk 'NR>1 {mem+=$4; cpu+=$3; count++} END {printf \"Processes: %d  Avg CPU: %.1f%%  Avg Mem: %.1f%%\\n\", count, cpu/count, mem/count}'",
    ),
    (
        "show top 3 CPU and memory consumers on one screen",
        "echo '--- CPU ---' && ps aux --sort=-%cpu | awk 'NR>1 && NR<5 {print $3\"% \"$11}' && echo '--- MEM ---' && ps aux --sort=-%mem | awk 'NR>1 && NR<5 {print $4\"% \"$11}'",
    ),
    (
        "compact kubernetes cluster summary",
        "echo \"Nodes: $(kubectl get nodes --no-headers | wc -l | tr -d ' ')  Pods: $(kubectl get pods --all-namespaces --no-headers | wc -l | tr -d ' ')  Services: $(kubectl get svc --all-namespaces --no-headers | wc -l | tr -d ' ')\"",
    ),
    (
        "show current directory summary in one line",
        "echo \"Files: $(ls | wc -l | tr -d ' ')  Dirs: $(ls -d */ 2>/dev/null | wc -l | tr -d ' ')  Size: $(du -sh . 2>/dev/null | cut -f1)  Git: $(git branch --show-current 2>/dev/null || echo none)\"",
    ),
    ("install the wget formula with homebrew", "brew install wget"),
    ("uninstall the imagemagick formula", "brew uninstall imagemagick"),
    ("upgrade a specific formula to the latest version", "brew upgrade ripgrep"),
    ("upgrade all outdated homebrew packages at once", "brew upgrade"),
    ("remove old versions of all homebrew formulas", "brew cleanup"),
    ("clean up homebrew packages older than 7 days", "brew cleanup --prune=7"),
    (
        "see how much disk space homebrew cleanup would free without deleting anything",
        "brew cleanup -n",
    ),
    ("search homebrew for a formula matching httpie", "brew search httpie"),
    ("show info and homepage for the jq formula", "brew info jq"),
    ("list all installed homebrew casks", "brew list --cask"),
    ("reinstall a broken or corrupted homebrew formula", "brew reinstall node"),
    ("update homebrew itself and the formula lists", "brew update"),
    ("pin a formula so it does not get upgraded", "brew pin python@3.12"),
    ("unpin a formula to allow upgrades again", "brew unpin python@3.12"),
    ("show which installed packages depend on openssl", "brew uses --installed openssl"),
    ("list all direct dependencies of the ffmpeg formula", "brew deps ffmpeg"),
    ("show the full dependency tree for a formula", "brew deps --tree ffmpeg"),
    ("add a package as a dev dependency using bun", "bun add -d vitest"),
    (
        "clean node_modules and reinstall everything from scratch",
        "rm -rf node_modules && bun install",
    ),
    ("start the dev server", "bun dev"),
    ("check what scripts are available in this project", "jq '.scripts' package.json"),
    ("check for outdated packages in this project", "npm outdated"),
    ("automatically fix low-severity vulnerabilities", "npm audit fix"),
    ("install a tool globally with npm", "npm install -g typescript"),
    ("uninstall a globally installed npm tool", "npm uninstall -g create-react-app"),
    ("find which installed package provides the jest binary", "npm ls jest"),
    ("check the version of a locally installed package", "jq '.dependencies.react' package.json"),
    ("show the full resolved version of every dependency", "bun pm ls"),
    ("print the bin path for a locally installed tool", "bun pm bin"),
    ("run a one-off npx tool without installing it", "npx cowsay hello"),
    ("check the bundle size of a package without installing it", "npx bundlephobia-cli axios"),
    (
        "scaffold a new vite project without globally installing vite",
        "npx create-vite@latest my-app",
    ),
    ("generate a new next.js app using npx", "npx create-next-app@latest my-app"),
    ("run prettier on all typescript files as a one-off", "npx prettier --write '**/*.ts'"),
    ("check the rust project for errors without producing a binary", "cargo check"),
    ("format all rust source files", "cargo fmt"),
    ("add a crate dependency to the project", "cargo add serde --features derive"),
    ("remove a crate dependency from the project", "cargo remove serde"),
    ("run a specific test by name", "cargo test test_parse_config"),
    ("run all tests and show output even for passing tests", "cargo test -- --nocapture"),
    ("show the full dependency tree for this rust project", "cargo tree"),
    ("update all dependencies to their latest compatible versions", "cargo update"),
    ("publish the crate to crates.io", "cargo publish"),
    ("run the project binary with arguments", "cargo run -- --help"),
    ("generate and open the documentation for this crate", "cargo doc --open"),
    ("check what features are available on a crate", "cargo add tokio --features full --dry-run"),
    ("audit rust dependencies for known security vulnerabilities", "cargo audit"),
    ("create a new python project with uv", "uv init my-project"),
    ("add a python package dependency with uv", "uv add httpx"),
    ("add a dev-only python dependency", "uv add --dev pytest"),
    ("remove a python package from the project", "uv remove httpx"),
    ("create a virtual environment in the current directory", "uv venv"),
    ("sync all dependencies from the lockfile", "uv sync"),
    ("run a python script inside the uv-managed environment", "uv run python script.py"),
    ("run a tool without installing it globally using uvx", "uvx ruff check ."),
    ("install a python tool globally with pipx", "pipx install black"),
    ("upgrade a globally installed pipx tool", "pipx upgrade ruff"),
    ("list all pipx-managed tools", "pipx list"),
    ("show the resolved dependency tree for a uv project", "uv tree"),
    ("lock the python dependencies without installing", "uv lock"),
    ("run pytest through uv", "uv run pytest"),
    ("show which python interpreter uv is using", "uv python pin"),
    (
        "what kind of project is this",
        "ls package.json Cargo.toml pyproject.toml Makefile go.mod 2>/dev/null",
    ),
    (
        "show project dependencies based on whatever system this uses",
        "{ [ -f package.json ] && jq '.dependencies' package.json; } || { [ -f Cargo.toml ] && cargo tree; } || { [ -f pyproject.toml ] && uv tree; }",
    ),
    (
        "lint the project using whichever linter is configured",
        "{ [ -f package.json ] && bun run lint; } || { [ -f Cargo.toml ] && cargo clippy --all-targets; } || { [ -f pyproject.toml ] && uvx ruff check .; }",
    ),
    (
        "check if the project builds successfully",
        "{ [ -f package.json ] && bun run build; } || { [ -f Cargo.toml ] && cargo build; } || { [ -f pyproject.toml ] && uv sync; }",
    ),
    (
        "run the project's test suite using the appropriate tool",
        "{ [ -f package.json ] && bun test; } || { [ -f Cargo.toml ] && cargo test; } || { [ -f pyproject.toml ] && uv run pytest; }",
    ),
    ("show the git remote URLs for this repository", "git remote -v"),
    (
        "show what changed since the last release tag",
        "git log $(git describe --tags --abbrev=0)..HEAD --oneline",
    ),
    (
        "count total lines of source code in this project",
        "find . -type f \\( -name '*.ts' -o -name '*.rs' -o -name '*.py' \\) -not -path '*/node_modules/*' -not -path '*/.venv/*' | xargs wc -l | tail -1",
    ),
    ("show the size of node_modules", "du -sh node_modules 2>/dev/null || echo 'no node_modules'"),
    (
        "check the node version required by this project",
        "jq '.engines.node' package.json 2>/dev/null || cat .nvmrc 2>/dev/null || cat .node-version 2>/dev/null",
    ),
    ("find unused dependencies in a typescript project", "npx depcheck"),
    (
        "generate a lockfile for the current bun project without installing",
        "bun install --frozen-lockfile --dry-run",
    ),
    (
        "show what changed in dependencies since the last lockfile commit",
        "git diff HEAD -- bun.lockb package.json Cargo.lock uv.lock",
    ),
    (
        "check if the lockfile is up to date without modifying anything",
        "bun install --frozen-lockfile",
    ),
    ("deduplicate dependencies in the npm lockfile", "npm dedupe"),
    ("show all transitive python dependencies including versions", "uv tree --depth 5"),
    (
        "find which dependency introduced a vulnerable package",
        "npm ls --all 2>/dev/null | grep -i <pkg>",
    ),
    ("check if a rust crate has any yanked versions in use", "cargo audit --deny yanked"),
    ("stop the server", "kill $(lsof -ti:3000)"),
    ("restart the app", "kill $(lsof -ti:3000); npm run dev"),
    ("what's running on port 8080", "lsof -i :8080"),
    ("kill whatever's on port 3000", "lsof -ti:3000 | xargs kill"),
    ("show me all node processes", "pgrep -fl node"),
    ("how much memory is my app using", "ps aux | grep -m1 node | awk '{print $6/1024 \"MB\"}'"),
    ("is the server running", "lsof -ti:3000 >/dev/null && echo running || echo stopped"),
    ("run this in the background", "nohup ./command &>/dev/null &"),
    ("show me everything that's running", "ps aux | sort -k3 -rn | head -20"),
    ("kill that process", "kill -9 $(pgrep -f process_name)"),
    ("watch the logs live", "tail -f /var/log/syslog"),
    ("run these jobs in parallel", "command1 & command2 & wait"),
    ("check if the API is up", "curl -sf http://localhost:8080/health && echo up || echo down"),
    ("how many threads is my app using", "ps -M $(pgrep node) | wc -l"),
    ("limit how much CPU that process uses", "cpulimit -p $(pgrep node) -l 50"),
    ("restart nginx", "sudo nginx -s reload"),
    ("show open network connections", "lsof -i -n -P | grep LISTEN"),
    ("stop all background jobs", "kill $(jobs -p)"),
    ("show me the big files", "du -sh * | sort -rh | head -10"),
    ("find that config file", "fd -t f config"),
    ("where's the package.json", "fd package.json"),
    ("what files changed today", "find . -mtime 0 -type f"),
    (
        "delete all node_modules folders",
        "find . -name node_modules -type d -prune -exec rm -rf {} +",
    ),
    ("show me hidden files", "eza -la --group-directories-first"),
    ("make this file executable", "chmod +x script.sh"),
    ("what's in this file", "bat file.txt"),
    ("copy file contents to clipboard", "pbcopy < file.txt"),
    ("show me the last thing I downloaded", "ls -lt ~/Downloads | head -5"),
    ("find files bigger than 100MB", "fd -t f --size +100m"),
    ("empty this directory but keep the folder", "rm -rf ./dir/* ./dir/.*  2>/dev/null; true"),
    ("show me recently modified files", "fd -t f --changed-within 1d"),
    ("rename all these files at once", 'for f in *.txt; do mv "$f" "${f%.txt}.md"; done'),
    ("compare these two files", "diff <(sort file1.txt) <(sort file2.txt)"),
    (
        "find all the TODO comments in the code",
        "rg --line-number 'TODO|FIXME|HACK' --glob '*.{ts,js,py}'",
    ),
    ("remove duplicate lines from this file", "awk '!seen[$0]++' file.txt > deduped.txt"),
    ("count the lines in all these files", "wc -l **/*.ts | sort -n"),
    ("show me the folder structure", "eza --tree --level=3"),
    ("make a backup of this file", "cp file.txt file.txt.$(date +%Y%m%d)"),
    ("where is that binary installed", "which node && node --version"),
    ("watch this file for changes", "fswatch -o file.txt | xargs -n1 -I{} cat file.txt"),
    ("show me only the files git doesn't know about", "git ls-files --others --exclude-standard"),
    ("what did I change", "git diff --stat"),
    ("save my work", "git add -A && git stash"),
    ("show me today's commits", "git log --oneline --since='midnight'"),
    ("who wrote this line", "git blame -L 42,42 file.py"),
    (
        "which branch has this fix",
        "git branch --contains $(git log --all --oneline | grep 'fix description' | awk '{print $1}')",
    ),
    ("make a new branch for this feature", "git checkout -b feature/my-feature"),
    ("push my branch", "git push -u origin $(git branch --show-current)"),
    (
        "clean up merged branches",
        "git branch --merged main | grep -v 'main\\|\\*' | xargs git branch -d",
    ),
    ("pull the latest changes", "git pull --rebase"),
    ("see what everyone else has been committing", "git log --oneline --all --since='1 week ago'"),
    ("squash my last three commits", "git rebase -i HEAD~3"),
    ("tag this release", "git tag -a v1.0.0 -m 'Release 1.0.0' && git push --tags"),
    (
        "find the commit that broke things",
        "git bisect start && git bisect bad HEAD && git bisect good v0.9.0",
    ),
    ("recover that file I deleted", "git checkout HEAD -- deleted-file.ts"),
    ("see what's staged", "git diff --cached --stat"),
    ("cherry-pick that fix from the other branch", "git cherry-pick <commit-hash>"),
    ("show me the full history of this file", "git log --follow --oneline -- path/to/file.ts"),
    ("how much RAM is free", "vm_stat | awk '/free/ {print $3 * 4096 / 1048576 \" MB free\"}'"),
    ("what's my macOS version", "sw_vers"),
    (
        "check my internet speed",
        "curl -s https://raw.githubusercontent.com/sivel/speedtest-cli/master/speedtest.py | python3",
    ),
    ("who's logged in", "w"),
    ("show battery percentage", "pmset -g batt | grep -o '[0-9]*%' | head -1"),
    (
        "what hardware am I running on",
        "system_profiler SPHardwareDataType | grep -E 'Model|Chip|Memory'",
    ),
    (
        "how hot is my CPU",
        "sudo powermetrics --samplers smc -n1 2>/dev/null | grep 'CPU die temperature'",
    ),
    ("show all env variables", "env | sort"),
    ("what shell am I using", "echo $SHELL && $SHELL --version"),
    ("check if a port is open", "nc -zv host 443 2>&1"),
    ("show my DNS servers", "scutil --dns | grep nameserver | sort -u"),
    ("what's eating disk space", "du -sh /* 2>/dev/null | sort -rh | head -10"),
    ("list all installed apps", "ls /Applications | sort"),
    ("what's my hostname", "hostname"),
    ("show kernel version", "uname -r"),
    ("connect to my server", "ssh user@host"),
    ("copy this file to the server", "scp file.txt user@host:~/"),
    ("tunnel port 3000 to remote", "ssh -L 3000:localhost:3000 user@host -N"),
    ("run a command on remote", "ssh user@host 'command && echo done'"),
    ("keep SSH alive", "ssh -o ServerAliveInterval=60 -o ServerAliveCountMax=3 user@host"),
    ("sync my local folder to the server", "rsync -avz --progress ./local/ user@host:~/remote/"),
    ("copy files from the server", "scp -r user@host:~/remote/ ./local/"),
    ("set up an SSH key", "ssh-keygen -t ed25519 -C 'me@example.com' && ssh-copy-id user@host"),
    ("check if I can reach the server", "ping -c 3 host"),
    ("jump through a bastion host", "ssh -J bastion_user@bastion_host target_user@target_host"),
    ("show running containers", "docker ps --format 'table {{.Names}}\\t{{.Status}}\\t{{.Ports}}'"),
    ("get into the container", "docker exec -it container_name sh"),
    ("check the logs", "docker logs -f --tail 50 container_name"),
    ("rebuild the image", "docker compose build --no-cache && docker compose up -d"),
    (
        "see how big my images are",
        "docker images --format 'table {{.Repository}}\\t{{.Tag}}\\t{{.Size}}' | sort -k3 -rh",
    ),
    ("copy a file out of the container", "docker cp container_name:/path/to/file ./"),
    ("restart just one service", "docker compose restart service_name"),
    ("show container resource usage", "docker stats --no-stream"),
    ("see the container's environment", "docker exec container_name env | sort"),
    ("push my image to the registry", "docker build -t myapp:latest . && docker push myapp:latest"),
    ("run a one-off command in the container", "docker compose run --rm service_name command"),
    ("generate a random password", "openssl rand -base64 32"),
    ("what time is it in UTC", "date -u"),
    ("convert this image to PNG", "sips -s format png image.jpg --out image.png"),
    ("compress this folder", "tar czf archive.tar.gz folder/"),
    ("calculate something quick", "python3 -c 'print(2**10)'"),
    ("open this URL", "open https://example.com"),
    ("timer for 5 minutes", "sleep 300 && say 'time is up'"),
    ("format this JSON", "pbpaste | python3 -m json.tool | pbcopy"),
    ("encode this string to base64", "echo -n 'hello' | base64"),
    ("show a calendar for this month", "cal"),
    ("search for TODO in all TypeScript files", "rg TODO -t ts"),
    ("find all function definitions in JavaScript files", "rg 'function \\w+' -t js"),
    ("search for a pattern ignoring case", "rg -i pattern ."),
    ("search and show only filenames with matches", "rg -l pattern ."),
    ("search with 3 lines of context around each match", "rg -C3 pattern ."),
    ("count matches per file", "rg -c pattern ."),
    ("search for pattern in the src directory only", "rg pattern src/"),
    ("search excluding node_modules", "rg pattern -g '!node_modules'"),
    ("find all imports of a specific module in TypeScript", "rg 'import.*from.*module' -t ts"),
    (
        "replace text across all files matching a pattern",
        "rg pattern -l | xargs sed -i '' 's/old/new/g'",
    ),
    ("search for pattern and show only the matching portion", "rg -o 'https?://[^\\s]+' ."),
    ("search across hidden files and directories", "rg --hidden pattern ."),
    ("search for multiline patterns", "rg -U 'start.*\\nend' ."),
    ("show files that do NOT match a pattern", "rg --files-without-match pattern ."),
    ("search with a fixed string instead of regex", "rg -F 'literal.string' ."),
    ("find files modified in the last hour", "fd --changed-within 1h"),
    ("find and delete all .DS_Store files", "fd -H .DS_Store -x rm"),
    ("find files larger than 10 megabytes", "fd -t f -S +10m"),
    ("find files matching a name pattern", "fd pattern"),
    ("find directories only matching a name", "fd -t d name"),
    ("find Python files and count their lines", "fd -e py -x wc -l"),
    ("find files excluding node_modules and .git", "fd pattern -E node_modules -E .git"),
    ("find all files owned by current user", "fd -t f --owner $(whoami)"),
    ("find executable files", "fd -t x"),
    ("find symlinks in a directory", "fd -t l"),
    (
        "find files modified between two dates",
        "fd --changed-after 2025-01-01 --changed-before 2025-06-01",
    ),
    (
        "find all json files and pretty-print them",
        "fd -e json -x sh -c 'echo \"=== {} ===\"; cat {}'",
    ),
    ("find empty files", "fd -t f --size 0"),
    ("find and open all markdown files in editor", "fd -e md -x $EDITOR"),
    ("show directory tree two levels deep", "eza --tree -L 2"),
    ("list files sorted by size", "eza -la --sort=size"),
    ("list only directories", "eza -D"),
    ("show git status alongside file list", "eza -la --git"),
    ("list files sorted by modification time", "eza -la --sort=modified"),
    ("show file tree with git status three levels deep", "eza --tree --git -L 3"),
    ("list all files including hidden ones with icons", "eza -la --icons --all"),
    ("show file sizes in bytes", "eza -la --bytes"),
    ("list files with their inode numbers", "eza -la --inode"),
    ("fuzzy find a file and open it in editor", "fd -t f | fzf | xargs $EDITOR"),
    ("fuzzy search and switch git branches", "git branch | fzf | xargs git checkout"),
    ("interactively kill a process by name", "ps aux | fzf | awk '{print $2}' | xargs kill"),
    (
        "fuzzy search command history and run selection",
        "history | fzf | awk '{$1=\"\"; print}' | bash",
    ),
    (
        "preview files with syntax highlighting while searching",
        "fd -t f | fzf --preview 'bat --color=always {}'",
    ),
    (
        "fuzzy search docker containers and tail logs",
        "docker ps --format '{{.Names}}' | fzf | xargs docker logs -f",
    ),
    ("interactive git log with commit preview", "git log --oneline | fzf --preview 'git show {1}'"),
    ("fuzzy select a directory and cd into it", 'fd -t d | fzf | read -r dir && cd "$dir"'),
    ("fuzzy find and checkout a git tag", "git tag | fzf | xargs git checkout"),
    (
        "fuzzy select an npm script and run it",
        "jq -r '.scripts | keys[]' package.json | fzf | xargs bun run",
    ),
    (
        "fuzzy pick a running docker container and exec into it",
        "docker ps --format '{{.Names}}' | fzf | xargs -I{} docker exec -it {} bash",
    ),
    ("fuzzy select a file and copy its path to clipboard", "fd -t f | fzf | pbcopy"),
    ("fuzzy search environment variables", "env | fzf"),
    (
        "fuzzy select a git stash and apply it",
        "git stash list | fzf | awk -F: '{print $1}' | xargs git stash apply",
    ),
    (
        "fuzzy find and delete a git branch",
        "git branch | grep -v '\\*' | fzf | xargs git branch -d",
    ),
    ("jump to the projects folder", "z projects"),
    ("jump to the most used directory matching a pattern", "z pattern"),
    ("open interactive directory picker", "zi"),
    ("add current directory to zoxide database", "zoxide add ."),
    ("list the ten most visited directories", "zoxide query -l | head -10"),
    ("find the ten largest files recursively", "fd -t f -x du -b | sort -rn | head -10"),
    (
        "count lines of code across TypeScript Python and Rust files",
        "fd -e ts -e py -e rs -x wc -l | sort -rn",
    ),
    (
        "show unique error types from a log file",
        "rg ERROR app.log | awk -F: '{print $NF}' | sort -u",
    ),
    (
        "find files with duplicate names across directories",
        "fd -t f | awk -F/ '{print $NF}' | sort | uniq -d",
    ),
    (
        "show top five most common HTTP status codes in access log",
        "awk '{print $9}' access.log | sort | uniq -c | sort -rn | head -5",
    ),
    (
        "fetch JSON from an API and format as an aligned table",
        "curl -s https://api.example.com/data | jq -r '.[] | [.name, .value] | @tsv' | column -t",
    ),
    (
        "watch source directory for changes and re-run tests",
        "fswatch -o src/ | xargs -n1 -I{} bun test",
    ),
    ("find all TODOs and format them as a markdown checklist", "rg TODO -n | sed 's/^/- [ ] /'"),
    ("extract all URLs from a file", "rg -o 'https?://[^\\s]+' file.txt"),
    ("show current disk usage percentage for root", "df -h / | awk 'NR==2{print $5}'"),
    ("list all processes sorted by memory usage", "ps aux | sort -rk 4 | head -10"),
    (
        "tail logs and highlight ERROR lines in red",
        "tail -f app.log | rg --passthru --color=always ERROR",
    ),
    ("find the most recently modified file in a directory", "fd -t f | xargs ls -t | head -1"),
    (
        "batch rename files replacing spaces with underscores",
        'fd -t f -e txt | xargs -I{} bash -c \'mv "$0" "${0// /_}"\' {}',
    ),
    (
        "count the number of each file extension in a project",
        "fd -t f | awk -F. '{print $NF}' | sort | uniq -c | sort -rn",
    ),
    (
        "show git diff stats piped through bat for syntax highlighting",
        "git diff --stat | bat -l diff",
    ),
    ("find all TODO FIXME and HACK comments", "rg 'TODO|FIXME|HACK' -t ts -t py -t rs"),
    ("list all npm dependencies with their versions as JSON", "jq '.dependencies' package.json"),
    ("search for a pattern across all git commits", "git log --all -p | rg pattern"),
    ("diff the output of two commands", "diff <(command1) <(command2)"),
    ("compare file listings between two directories", "diff <(ls dir1) <(ls dir2)"),
    ("combine head of one file with tail of another", "cat <(head -20 file1) <(tail -20 file2)"),
    ("open the first file matching a pattern in the editor", "vim $(fd -t f pattern | head -1)"),
    (
        "source env file if it exists otherwise warn",
        "test -f .env && source .env || echo 'no .env found'",
    ),
    ("feed two sorted files into a join operation", "join <(sort file1) <(sort file2)"),
    (
        "run a command for each line of a variable",
        'while IFS= read -r line; do echo "$line"; done <<< "$multiline_var"',
    ),
    (
        "check if a command exists before running it",
        "command -v rg &>/dev/null && rg TODO . || grep -r TODO .",
    ),
    ("time a command and print elapsed seconds", "time (bun test 2>&1) 2>&1 | tail -1"),
    ("run the default just recipe", "just"),
    ("run a specific just recipe", "just recipe-name"),
    ("run a just recipe with arguments", "just deploy staging"),
    ("show a recipe definition without running it", "just --show recipe-name"),
    ("run a recipe from a specific justfile", "just -f path/to/justfile recipe"),
    ("check which justfile would be used", "just --justfile"),
    ("run just with verbose output for debugging", "just --verbose recipe-name"),
    ("evaluate and print a just variable", "just --evaluate var_name"),
    ("choose a recipe interactively from a menu", "just --choose"),
]
