"""
Merge Expert Pair Segments
===========================
Combines expert pair files generated by multiple agents (Amp, Codex, Gemini,
Cursor) into a single deduplicated expert_pairs.py file.

Usage:
    python merge_expert_segments.py

Input: data/expert-segments/*_pairs.py (each defines PAIRS = [...])
Output: expert_pairs.py (combined, deduplicated, categorized)
"""

from __future__ import annotations

import importlib.util
import sys
from pathlib import Path


def load_pairs_from_file(filepath: Path) -> list[tuple[str, str]]:
    """Dynamically import a Python file and extract its PAIRS variable."""
    spec = importlib.util.spec_from_file_location("segment", filepath)
    if spec is None or spec.loader is None:
        print(f"  [WARN] Cannot load {filepath}")
        return []

    module = importlib.util.module_from_spec(spec)
    try:
        spec.loader.exec_module(module)
    except Exception as exc:
        print(f"  [WARN] Error loading {filepath}: {exc}")
        return []

    # Try both PAIRS and EXPERT_PAIRS variable names
    pairs = getattr(module, "PAIRS", None) or getattr(module, "EXPERT_PAIRS", [])
    if not isinstance(pairs, list):
        print(f"  [WARN] {filepath} has no PAIRS or EXPERT_PAIRS list")
        return []

    return [(str(nl).strip(), str(cmd).strip()) for nl, cmd in pairs if nl and cmd]


def deduplicate_pairs(pairs: list[tuple[str, str]]) -> list[tuple[str, str]]:
    """Deduplicate by shell command (keep first occurrence)."""
    seen_cmds: set[str] = set()
    unique: list[tuple[str, str]] = []
    for nl, cmd in pairs:
        if cmd not in seen_cmds:
            seen_cmds.add(cmd)
            unique.append((nl, cmd))
    return unique


def main() -> None:
    segments_dir = Path(__file__).parent / "data" / "expert-segments"
    output_file = Path(__file__).parent / "expert_pairs.py"

    if not segments_dir.exists():
        print(f"No segments directory found at {segments_dir}")
        sys.exit(1)

    segment_files = sorted(
        list(segments_dir.glob("*_pairs.py")) + list(segments_dir.glob("segment_*.py"))
    )
    if not segment_files:
        print(f"No *_pairs.py files found in {segments_dir}")
        sys.exit(1)

    all_pairs: list[tuple[str, str]] = []

    print("Loading expert pair segments:")
    for filepath in segment_files:
        agent_name = filepath.stem.replace("_pairs", "")
        pairs = load_pairs_from_file(filepath)
        print(f"  {agent_name}: {len(pairs)} pairs")
        all_pairs.extend(pairs)

    # Also load existing expert_pairs.py if it exists (from engineer agent)
    if output_file.exists():
        existing = load_pairs_from_file(output_file)
        if existing:
            print(f"  existing expert_pairs.py: {len(existing)} pairs")
            all_pairs.extend(existing)

    print(f"\nTotal raw pairs: {len(all_pairs)}")

    unique_pairs = deduplicate_pairs(all_pairs)
    print(f"After dedup by command: {len(unique_pairs)}")

    # Write the merged file
    lines = [
        '"""',
        "NL2Shell Expert Pairs — Senior Engineer Quality",
        "=" * 50,
        "Combined from multiple AI agents (Amp, Codex, Gemini, Cursor)",
        "and hand-curated examples. Each pair represents how a 10+ year",
        "senior engineer would write the command.",
        "",
        f"Total: {len(unique_pairs)} expert-quality pairs",
        '"""',
        "",
        "",
        "EXPERT_PAIRS: list[tuple[str, str]] = [",
    ]

    for nl, cmd in unique_pairs:
        # Escape any quotes in the strings
        nl_escaped = nl.replace("\\", "\\\\").replace('"', '\\"')
        cmd_escaped = cmd.replace("\\", "\\\\").replace('"', '\\"')
        lines.append(f'    ("{nl_escaped}", "{cmd_escaped}"),')

    lines.append("]")
    lines.append("")

    output_file.write_text("\n".join(lines))
    print(f"\nWritten {len(unique_pairs)} pairs to {output_file}")


if __name__ == "__main__":
    main()
